openapi: 3.0.3
info:
  title: Racetag Backend API
  version: 0.1.0
servers:
  - url: http://localhost:8000
paths:
  /events/tag/batch:
    post:
      summary: Ingest a batch of tag events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/TagEventDTO'
      responses:
        '200':
          description: Batch accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  accepted:
                    type: integer
  /classification:
    get:
      summary: Current classification standings
      responses:
        '200':
          description: Standings ordered by race rules
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  standings:
                    type: array
                    items:
                      $ref: '#/components/schemas/ParticipantDTO'
  /race:
    get:
      summary: Race state
      responses:
        '200':
          description: Current race metadata and participants
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_laps:
                    type: integer
                  start_time:
                    type: string
                    format: date-time
                  participants:
                    type: array
                    items:
                      $ref: '#/components/schemas/ParticipantDTO'
  /stream:
    get:
      summary: Server-Sent Events stream for live updates
      responses:
        '200':
          description: SSE stream of lap and standings updates
          content:
            text/event-stream:
              schema:
                type: string
components:
  schemas:
    TagEventDTO:
      type: object
      required: [source, reader_ip, reader_serial, timestamp, event_type, tag_id]
      properties:
        source:
          type: string
          example: sirit-510
        reader_ip:
          type: string
        reader_serial:
          type: string
        timestamp:
          type: string
          description: ISO8601 with milliseconds and Z
          example: 2025-10-16T11:53:32.298Z
        event_type:
          type: string
          enum: [arrive, depart]
        tag_id:
          type: string
          description: Uppercase hex without 0x
        session_id:
          type: integer
          nullable: true
        antenna:
          type: integer
          nullable: true
        rssi:
          type: integer
          nullable: true
        first:
          type: string
          nullable: true
        last:
          type: string
          nullable: true
    ParticipantDTO:
      type: object
      required: [tag_id, laps, finished]
      properties:
        tag_id:
          type: string
        laps:
          type: integer
        last_pass_time:
          type: string
          nullable: true
        finish_time:
          type: string
          nullable: true
        finished:
          type: boolean
        total_time_ms:
          type: integer
          nullable: true
