# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-10-16T20:59:03+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class EventType(Enum):
    arrive = 'arrive'
    depart = 'depart'


class TagEventDTO(BaseModel):
    source: str = Field(..., example='sirit-510')
    reader_ip: str
    reader_serial: str
    timestamp: str = Field(
        ...,
        description='ISO8601 with milliseconds and Z',
        example='2025-10-16T11:53:32.298Z',
    )
    event_type: EventType
    tag_id: str = Field(..., description='Uppercase hex without 0x')
    session_id: Optional[int] = None
    antenna: Optional[int] = None
    rssi: Optional[int] = None
    first: Optional[str] = None
    last: Optional[str] = None


class ParticipantDTO(BaseModel):
    tag_id: str
    laps: int
    last_pass_time: Optional[str] = None
    finish_time: Optional[str] = None
    finished: bool
    total_time_ms: Optional[int] = None
